api_branch : origin/master
api_parser : ~
api_cfgmod : clone
api_runner : ~
api_paths  : src
env_make   : ~
env_prep   : get-composer
env_post   : ci-coveralls,ci-codacy
php_conf   : timezone
php_exts   : ~
app_prep   : dep-composer
app_post   : ~
app_path   : bin/arthur-doctrine-behavior
pkg_name   : arthur-doctrine-behavior-bundle
pkg_desc   : "a set of Doctrine subscribers to provide different behaviors, such as updated_on, create_on, published, etc."
pkg_bndl   : true
