<?php

/*
 * This file is part of the Scribe Mantle Bundle.
 *
 * (c) Scribe Inc. <source@scribe.software>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace Scribe\Arthur\DoctrineBehaviorBundle\Model\Slugable;

/**
 * Class SlugableBehaviorStaticTrait.
 */
trait SlugableBehaviorStaticTrait
{
    use SlugableBehaviorTrait {
        SlugableBehaviorTrait::initializeSlugAutoGenerated as disabledInitializeSlugAutoGenerated;
    }

    /**
     * @return $this
     */
    public function initializeSlugAutoGenerated()
    {
        $this->slugAutoGenerated = false;

        return $this;
    }

    /**
     * @return array
     */
    public function getAutoSlugFields()
    {
        return [];
    }
}

/* EOF */
